spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog_configuration
    username: kanokna
    password: kanokna_dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092

logging:
  level:
    com.kanokna.catalog: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
